apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc-10
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: host-pv
  resources:
    requests:
      storage: 10Mi
# kubectl apply -f ex11-my-pvc.yaml
