# ConfigMap, secret 를 pod 에서 참조해서 사용하는 실습예제.

apiVersion: v1
kind: Pod
metadata:
  name: my-config-secret-pod
spec:
  containers:
    - name: my-container
      image: nginx
      # 컨테이너에서 사용할 환경변수 설정
      env:
        # 환경변수 1
        - name: DB_HOST
          # configMap 을 참조해서 환경 변수 1 을 초기화
          valueFrom:
            configMapKeyRef:
              # configMap 중에서 my-config 의 configMap 를 참조
              name: my-config
              # my-config 의 key 중에서 db_host key 를 참조
              # db_host 의 value 를 참조해서 DB_HOST 를 초기화
              key: db_host
        # 환경변수 2
        - name: DB_PASSWORD
          # secret 객체 참조
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: DB_PW
# kubectl apply -f ex8-config-secret-pod.yaml

# kubectl exec my-config-secret-pod -- printenv
