# factorial-cache-app-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-factorial-cache-app
  namespace: factorial
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: factorial-cache-app
  template:
    metadata:
      labels:
        app: factorial-cache-app
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: factorial-cache-app
          image: diversim90/factorial-cache-app-for-k8s:0.0.2
          env:
            - name: APP_LANGUAGE
              valueFrom:
                configMapKeyRef:
                  name: factorial-config
                  key: laguage